implemented method to hash data
ADORSYS-GIS/e2e-banking-app pull request #102
Opened 2024-03-21 12:43 UTC by Awambeng

2024-03-21 13:31 UTC, Awambeng commented
done already

2024-03-21 13:53 UTC, Awambeng commented
@stephane-segning we completed ticket [Implement a logic to hash and validate strings #14](https://github.com/ADORSYS-GIS/e2e-banking-app/issues/14) you can now review

2024-03-23 21:51 UTC, stephane-segning requested changes
Good work @Awambeng ! You shouldn't make the service from the user repo btw. See these points

2024-03-23 21:51 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/utils/DataSecurityService.java
> +    }
This should not have something to do with users. Just plain simple hash comparison with the real value. E.g `compareHashWithPassword("dlskdksd", "real-passord")`.

2024-03-24 18:16 UTC, Awambeng commented
@stephane-segning work done as requested you can now review

2024-03-26 06:59 UTC, stephane-segning commented
Your code does not compile. Please fix that @Awambeng @stephane-segning @forkimenjeckayang @chendiblessing

2024-03-26 12:46 UTC, stephane-segning requested changes
Something's wrong in your implementation. Please refer to the official documentation of spring boot passwordencoder to validate your implementation of the check password. What you did cannot work.

2024-03-31 07:46 UTC, chendiblessing commented
@stephane-segning Did some changes on the test compare hash function please review it

2024-04-01 13:13 UTC, stephane-segning approved these changes
Well done! Thank you @Awambeng @stephane-segning @chendiblessing @forkimenjeckayang

2024-04-01 13:15 UTC, merged