Okpage and api faking implementation
ADORSYS-GIS/e2e-banking-app pull request #106
Opened 2024-03-25 12:05 UTC by ValantineSuh

Implemented the Ok Confirmation Page and faked a Send_Money API

2024-03-26 07:16 UTC, stephane-segning approved these changes
Awesome work!

2024-03-26 07:16 UTC, stephane-segning commented on power-pay-frontend/src/main.tsx
Cancel changes made in this file please

2024-03-26 07:17 UTC, stephane-segning requested changes
Please remove unrelated changes

2024-03-26 08:36 UTC, ValantineSuh commented
> Awesome work!

Thank you Sir

2024-03-26 14:13 UTC, stephane-segning commented on power-pay-frontend/src/main.tsx
Cancel all changes from this file

2024-03-26 14:14 UTC, stephane-segning commented on power-pay-frontend/src/App.css
Good. How can you do this using only `tailwindcss`?

2024-03-27 12:27 UTC, stephane-segning requested changes

2024-03-27 12:27 UTC, stephane-segning commented on power-pay-frontend/src/main.tsx
Cancel all changes from this file

2024-04-02 15:11 UTC, ValantineSuh commented
Hello @stephane-segning  due to the unverified and the partially verified commits on this our branch as you could see, we had to delete the branch but we forgot to cancel the pull request. 
Consequently, this ticket was repeated by @Motouom  and @ValantineSuh  and we made a pull request and it was approved and merged.
- https://github.com/ADORSYS-GIS/e2e-banking-app/pull/110

2024-04-02 15:13 UTC, ValantineSuh commented
So sir @stephane-segning, this pull request is to be closed, if it's okay by you.

> Hello @stephane-segning due to the unverified and the partially verified commits on this our branch as you could see, we had to delete the branch but we forgot to cancel the pull request. Consequently, this ticket was repeated by @Motouom and @ValantineSuh and we made a pull request and it was approved and merged.
> 
> * [Implement the frontend page for "ok" using ppa and api faking#27 #110](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/110)

So sir @stephane-segning, this pull request is to be closed, if it's okay by you.

2024-04-02 17:53 UTC, closed without merging