Implement the user registration logic
ADORSYS-GIS/e2e-banking-app pull request #107
Opened 2024-03-25 16:29 UTC by Awambeng

In this pr we implemented a method to create a user, generate an otp and hash its value and finally returned the procedure Id to the user upon creation.

2024-03-25 16:33 UTC, Awambeng commented
@stephane-segning pr for ticket [Implement the Logic for Creating a User in the backend #12](https://github.com/ADORSYS-GIS/e2e-banking-app/issues/12)

2024-03-26 06:58 UTC, stephane-segning commented
Your code is not building. You should fix that @Awambeng @forkimenjeckayang @chendiblessing @mbunwe-victor please

2024-03-26 12:57 UTC, stephane-segning requested changes
Good work. You'll need to adjust these points

2024-03-26 13:36 UTC, forkimenjeckayang commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/services/UserRegistrationService.java
Greetings @stephane-segning , we used int because creating a user will initiate a process and we have to return the process ID to the user. Also the class procedure is marked as an entity with “id” as primary key of type integer which is automatically incremented when a new procedure begins

2024-04-01 13:08 UTC, stephane-segning requested changes
Better work already. But some points can still be refined:

2024-04-01 13:08 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/services/UserRegistrationServiceImpl.java
> +    }
This logic is missing a lot of points. 
1. You should add attributes to the created user object (and hash the pin while you're at it)
2. You should not create a userRegistration object here, but call the related repo to find the one corresponding to the provided ID.

2024-04-01 13:08 UTC, stephane-segning commented on power-pay-backend/src/test/java/com/adorsys/gis/powerpay/powerpaybackend/utils_test/CompareHashPasswordTest.java
This test will fail

2024-04-11 09:50 UTC, Koufan-De-King approved these changes

2024-04-11 09:52 UTC, Christiantyemele approved these changes

2024-04-12 07:09 UTC, merged