feature: service worker
ADORSYS-GIS/e2e-banking-app pull request #109
Opened 2024-03-26 15:03 UTC by Ogenbertrand

2024-03-27 22:16 UTC, Ogenbertrand commented
@stephane-segning 
The service worker is modified i used pwa plugins to implement it.
[Add vite pwa plugins](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/109/commits/a462d5f8f3674ee8cddc4c4cad72b1ba41141893)

2024-04-01 13:04 UTC, stephane-segning requested changes
Good work @Ogenbertrand !

2024-04-01 13:04 UTC, stephane-segning commented on power-pay-frontend/dev-dist/registerSW.js
This folder `dev-dist` should be removed from the vcs

2024-04-01 13:04 UTC, stephane-segning commented on power-pay-frontend/dev-dist/sw.js
This folder `dev-dist` should be removed from the vcs

2024-04-01 13:04 UTC, stephane-segning commented on power-pay-frontend/dev-dist/workbox-b5f7729d.js
This folder `dev-dist` should be removed from the vcs

2024-04-01 13:04 UTC, stephane-segning commented on power-pay-frontend/src/main.tsx
Cancel unuseful changes

2024-04-01 13:21 UTC, Ogenbertrand commented on power-pay-frontend/src/main.tsx
okay sir

2024-04-02 09:52 UTC, Ogenbertrand commented
@stephane-segning 
[Remove dev-dist folder and its contents from VCS](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/109/commits/fec549b62d9f7fd1b79a43a3ddf4521a3bd03827)

2024-04-02 09:56 UTC, stephane-segning approved these changes
Good work @Ogenbertrand !

2024-04-02 09:57 UTC, merged