update on ticket "Implement the frontend page for "ok" using ppa and api faking#27"
ADORSYS-GIS/e2e-banking-app pull request #127
Opened 2024-04-10 11:11 UTC by Motouom

2024-04-10 11:17 UTC, Motouom commented
Hello @stephane-segning, @Arielpetit, @Christiantyemele   review PR

2024-04-11 08:19 UTC, Christiantyemele commented
Good job! 👍  @Motouom but please undo the changes in the main.tsx

2024-04-11 08:20 UTC, Christiantyemele commented on power-pay-frontend/src/main.tsx
> +    <OKPage />
please undo this change its not neccessary in the main

2024-04-11 08:28 UTC, Arielpetit approved these changes
Good

2024-04-11 10:57 UTC, Christiantyemele approved these changes

2024-04-12 08:27 UTC, stephane-segning requested changes

2024-04-12 08:27 UTC, stephane-segning commented on power-pay-frontend/dev-dist/registerSW.js
Why am I seeing this file in this PR?

2024-04-12 08:27 UTC, stephane-segning commented on power-pay-frontend/src/components/okpage.tsx
The OK Page is supposed to be a layout. So you can split this into multiple components

2024-04-12 23:43 UTC, stephane-segning approved these changes

2024-04-15 08:04 UTC, closed without merging