Implement the frontend page for recipient's data input using ppa #26
ADORSYS-GIS/e2e-banking-app pull request #131
Opened 2024-04-12 14:50 UTC by Ngha-Boris

2024-04-12 15:17 UTC, Motouom requested changes

2024-04-12 15:17 UTC, Motouom commented on power-pay-frontend/src/main.tsx
Please remove unnecessary imports here

2024-04-12 15:18 UTC, Motouom commented
Please also make sure that your front-end matches with the mock-up that was provided.

2024-04-15 11:13 UTC, Motouom reviewed
please also send the output of the front-end pages so that we see what it looks like
for 
- the input option page
- the qr-scan page
- input manually page
@Ngha-Boris @Blindspot22 @Tekum-Emmanuella

2024-04-15 11:25 UTC, Ngha-Boris commented
> please also send the output of the front-end pages so that we see what it looks like for
> 
> * the input option page
> * the qr-scan page
> * input manually page
>   @Ngha-Boris @Blindspot22 @Tekum-Emmanuella

ok on it

2024-04-15 12:26 UTC, Motouom commented
![image](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/3f8d3d5b-79b1-45dc-8714-a407a2541ada)

the QR-scan has to be in a new page and on on the same page as the input option

2024-04-17 09:04 UTC, stephane-segning requested changes
Focus on these points too please

2024-04-17 09:04 UTC, stephane-segning commented on power-pay-frontend/src/components/scan_rq.tsx
> +  };
You should do a real handling of these cases.

2024-04-17 09:04 UTC, stephane-segning commented on power-pay-frontend/src/components/index.tsx
Rename this file into something more specific

2024-04-17 09:04 UTC, stephane-segning commented on power-pay-frontend/src/components/fake_api.tsx
> +const FakeApi = () => {
Use small letters for this one

2024-04-17 09:10 UTC, Tekum-Emmanuella commented
I have updated the userinfo for manual input and  made it responsive.

2024-04-17 09:14 UTC, Tekum-Emmanuella commented
the userinfo for manual input has been made responsive sir


On Mon, Apr 15, 2024 at 1:26 PM Motouom Victoire ***@***.***>
wrote:

> image.png (view on web)
> <https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/3f8d3d5b-79b1-45dc-8714-a407a2541ada>
>
> the QR-scan has to be in a new page and on on the same page as the input
> option
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ADORSYS-GIS/e2e-banking-app/pull/131#issuecomment-2056731835>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDYXUCFKK23JBD3N5DH2C63Y5PBQJAVCNFSM6AAAAABGEJDGE6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANJWG4ZTCOBTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-17 09:14 UTC, Blindspot22 commented
> I have updated the userinfo for manual input and made it responsive.

@Tekum-Emmanuella Please learn to always tag people when replying their message

2024-04-17 15:43 UTC, Tekum-Emmanuella commented
> > I have updated the userinfo for manual input and made it responsive.
> 
> @Tekum-Emmanuella Please learn to always tag people when replying their message it alerts them more precisely
Thank you @Blindspot22

2024-04-17 16:18 UTC, Tekum-Emmanuella commented
> Please also make sure that your front-end matches with the mock-up that was provided.

ok @Motouom

2024-04-17 16:29 UTC, Tekum-Emmanuella commented
> Please also make sure that your front-end matches with the mock-up that was provided.

ok @Motouom

2024-04-17 16:30 UTC, Tekum-Emmanuella commented
> > Please also make sure that your front-end matches with the mock-up that was provided.
> 
> ok @Motouom

ok @Motouom

2024-04-17 16:30 UTC, Tekum-Emmanuella commented
@Motouom

2024-04-17 18:10 UTC, Koufan-De-King approved these changes
@Ngha-Boris I see the tests are now successful. As far as I can see, all good.

2024-04-22 11:55 UTC, Ngha-Boris commented
![qrscanner](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/148923719/d9cc09f6-cc97-4e7b-9eca-525352cfecc5)

2024-04-22 11:56 UTC, Motouom approved these changes
OKAY GOOD!

2024-04-22 12:05 UTC, mbunwe-victor approved these changes

2024-04-23 07:41 UTC, Ngha-Boris commented
> Focus on these points too please

done

2024-04-23 07:44 UTC, Ngha-Boris reviewed
All changes made

2024-04-23 13:03 UTC, stephane-segning requested changes

2024-04-23 13:03 UTC, stephane-segning commented on paymentoption.tsx
What is the use of this item here?

2024-04-23 14:38 UTC, Tekum-Emmanuella commented on paymentoption.tsx
It's the user interface where he/she can send money either manually or by scanning

2024-04-23 14:42 UTC, Tekum-Emmanuella commented on paymentoption.tsx
It's the user interface where he/she can send money either manually or by scanning @stephane-segning

2024-05-06 20:07 UTC, stephane-segning requested changes

2024-05-06 20:07 UTC, stephane-segning commented on power-pay-frontend/src/components/userinfo.tsx
> +const UserInfo: React.FC = () => {
Rename this to the according related component's name

2024-05-06 20:07 UTC, stephane-segning commented on power-pay-frontend/src/components/scan_rq.tsx
> +const QRScannerComponent  = () => {
You might need some props for passing data in and out

2024-05-06 20:07 UTC, stephane-segning commented on power-pay-frontend/src/components/route.tsx
> + from "./scan_rq";
Format this well

2024-05-06 20:07 UTC, stephane-segning commented on paymentoption.tsx
> +const PaymentOptions: React.FC = () => {
This might need some props to manage the IO of this component from the outside

2024-05-07 07:29 UTC, Tekum-Emmanuella commented
Good morning .@Mr.stephane. please all the above changes you requested for have been resolved.

2024-05-07 10:42 UTC, stephane-segning approved these changes

2024-05-07 10:43 UTC, stephane-segning requested changes

2024-05-07 10:43 UTC, stephane-segning commented on paymentoption.tsx
Remove this component from the root

2024-06-11 15:55 UTC, Motouom approved these changes

2024-06-11 16:05 UTC, Arielpetit approved these changes

2024-06-11 18:14 UTC, stephane-segning requested changes

2024-06-11 18:14 UTC, stephane-segning commented on power-pay-frontend/src/components/paymentoption.tsx
> +          <button onClick={handleScanQRClick} className="bg-blue-950 rounded-full w-80 m-auto px-4  text-white text-lg absolute  inset-x-0 bottom-12">
Add `type` `button` to this button, because it's not for a `form` tag

2024-06-12 08:02 UTC, stephane-segning approved these changes

2024-06-12 08:10 UTC, merged