registration page creation
ADORSYS-GIS/e2e-banking-app pull request #132
Opened 2024-04-15 08:04 UTC by ndefokou

registration page creation

2024-04-16 06:29 UTC, Ngha-Boris requested changes

2024-04-16 06:29 UTC, Ngha-Boris commented on power-pay-frontend/dev-dist/registerSW.js
Hello @ndefokou what is this file doing in this PR please consider this.

2024-04-16 06:29 UTC, Ngha-Boris commented on power-pay-frontend/dev-dist/workbox-b5f7729d.js
Hello @ndefokou what is this file doing in this PR please consider this.

2024-04-16 06:29 UTC, Ngha-Boris commented on power-pay-frontend/dev-dist/sw.js
Hello @ndefokou what is this file doing in this PR please consider this.

2024-04-16 06:33 UTC, Ngha-Boris commented
Please @ndefokou  also send a screenshot of the user registration front-end page so that we see how it looks like.

2024-04-17 06:38 UTC, ndefokou commented
@Motouom done

2024-04-17 14:33 UTC, Motouom commented on power-pay-frontend/src/components/RegistrationForm.tsx
You can also remove the validation logic from here and also extract it into a separate component

2024-04-17 17:53 UTC, Koufan-De-King approved these changes
@Ngha-Boris 
I see the tests are now working. Looks good.

2024-04-17 18:07 UTC, Koufan-De-King requested changes
@ndefokou Consider the changes asked by @Ngha-Boris

2024-04-18 15:00 UTC, ndefokou commented
@Koufan-De-King @Motouom done

2024-04-18 16:39 UTC, ndefokou commented
![Screenshot from 2024-04-18 17-38-53](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/150008782/4c094961-be93-4ff2-96a9-b4796c8ad708)
![Screenshot from 2024-04-18 17-38-43](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/150008782/aadb8134-ef9a-4113-8ee5-b09077466ebf)
![Screenshot from 2024-04-18 17-38-06](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/150008782/831dbfee-3914-4113-816a-a63b98e8142b)

2024-04-18 16:39 UTC, ndefokou commented
@Ngha-Boris hier is it

2024-04-18 17:53 UTC, Ngha-Boris requested changes
Hello Mr @ndefokou please check the mock-up that Sinke sent in the Spring-jobs channel on discord and ensure that your mock-up is exactly like what  Sinke had sent that is for the part that concern you.

2024-04-19 07:23 UTC, Motouom commented
> ![Screenshot from 2024-04-18 17-38-53](https://private-user-images.githubusercontent.com/150008782/323689454-4c094961-be93-4ff2-96a9-b4796c8ad708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTE0NTMsIm5iZiI6MTcxMzUxMTE1MywicGF0aCI6Ii8xNTAwMDg3ODIvMzIzNjg5NDU0LTRjMDk0OTYxLWJlOTMtNGZmMi05NmE5LWI0Nzk2YzhhZDcwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNzE5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDhhY2ZiNmFkNjBkOWRiMzAwNGQzMmMyOTJiZDNjNDA4NmM3YzA4MGY4ZjU0NTJjNDkwODVkMjI3Mjk4NTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6j4H8ngSO4fJJBq2pIlh_T8UVpiMh0kUhBJ2AldK_zg) ![Screenshot from 2024-04-18 17-38-43](https://private-user-images.githubusercontent.com/150008782/323689470-aadb8134-ef9a-4113-8ee5-b09077466ebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTE0NTMsIm5iZiI6MTcxMzUxMTE1MywicGF0aCI6Ii8xNTAwMDg3ODIvMzIzNjg5NDcwLWFhZGI4MTM0LWVmOWEtNDExMy04ZWU1LWIwOTA3NzQ2NmViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNzE5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01N2RhZmMxOTFkNWJjMTNjY2RmM2NhMTExNTlhOWMxYTQ1ZjRkMzk4YzFmYTRlMTI4ZjZlYmJjMTY4Yzk0NTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sqnfEkK-GzHyQ2qOeiKP8NjWa3MN5fWsDTYOGFLCTpk) ![Screenshot from 2024-04-18 17-38-06](https://private-user-images.githubusercontent.com/150008782/323689481-831dbfee-3914-4113-816a-a63b98e8142b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTE0NTMsIm5iZiI6MTcxMzUxMTE1MywicGF0aCI6Ii8xNTAwMDg3ODIvMzIzNjg5NDgxLTgzMWRiZmVlLTM5MTQtNDExMy04MTZhLWE2M2I5OGU4MTQyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNzE5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjE0MjdhZWY2ZTVmMjkxYjQ3ZmEzNGIxNDJiNzAxZGYxZGRhYTkzM2QzM2IzZmIwMGEzNjM2OWZjMTM0YmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3993VNr0D9T0OEewBQympG80-YU-JByDjWOozDhZ6Bw)

@ndefokou  This is your Mockup please make sure it looks the same. The only problem on the mockup is that the pin input field was forgotten. Never the less your output needs to match your mockup
![image](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/e1e51f86-21ec-47b6-b56e-315729582320)

2024-04-19 09:35 UTC, Motouom commented
> ![Screenshot from 2024-04-19 09-39-41](https://private-user-images.githubusercontent.com/150008782/323891487-5a9dec18-24b9-4051-8632-c4c46b5bf110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTk1OTAsIm5iZiI6MTcxMzUxOTI5MCwicGF0aCI6Ii8xNTAwMDg3ODIvMzIzODkxNDg3LTVhOWRlYzE4LTI0YjktNDA1MS04NjMyLWM0YzQ2YjViZjExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwOTM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWRiODI5MDVlYzliODEwMmM3ZjYxMWMyMzcwZTdkMjkyNTNiMWU1ZGVhYWE3ZWVkODNlNjU4NThiNmIzNDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LzZzDFIDQuympv6jU57gtsAPGj5rGdH9mQsn_jOWAFw) ![Screenshot from 2024-04-19 09-39-30](https://private-user-images.githubusercontent.com/150008782/323891499-c11799d6-69e8-4974-ac98-e178a0cb50e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTk1OTAsIm5iZiI6MTcxMzUxOTI5MCwicGF0aCI6Ii8xNTAwMDg3ODIvMzIzODkxNDk5LWMxMTc5OWQ2LTY5ZTgtNDk3NC1hYzk4LWUxNzhhMGNiNTBlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwOTM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGU0NzY0MDY3MzVjYThmMzc4ODkyMmU5MDhjYzdkMTZiNWQ3YTY0Y2M0MzBjOWFhZTEwODJlMTgwODk2MzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DAUTejP0HFep1KYyOtUe1JWZEmdaf3UUNd9yM29deSA) @Ngha-Boris @Motouom hier is the correction

Awesome @ndefokou

2024-04-19 09:52 UTC, ndefokou commented
@Ngha-Boris the correction is above

2024-04-19 12:57 UTC, Motouom commented
@ndefokou  Please you should also add a Login button in the registration page such that if the user does have an account already he/she can just click there and it will take him to the login page.

The Login page has already been created so you just need to add the button and that is all

2024-04-19 13:05 UTC, Koufan-De-King approved these changes

2024-04-22 08:33 UTC, ndefokou commented
![Screenshot from 2024-04-22 09-32-23](https://github.com/ADORSYS-GIS/e2e-banking-app/assets/150008782/364997a0-fac9-4e33-b2d8-efb8522d5c24)
@Motouom

2024-04-22 08:34 UTC, Motouom approved these changes

2024-04-22 08:36 UTC, Koufan-De-King approved these changes
Looks alright.

2024-04-22 08:41 UTC, Ngha-Boris approved these changes

2024-04-22 08:45 UTC, Ngha-Boris approved these changes

2024-04-22 08:48 UTC, Ngha-Boris requested changes
Please @ndefokou  ensure that all your commits are signed

2024-04-22 09:40 UTC, Ngha-Boris approved these changes

2024-04-22 10:01 UTC, merged