feat(backend): Implemented the rest API for sendMoney
ADORSYS-GIS/e2e-banking-app pull request #139
Opened 2024-06-11 16:16 UTC by kouamschekina

Introduced the SendMoneyController to facilitate the initiation of money transfers within our banking application

2024-06-11 18:12 UTC, stephane-segning requested changes
Good work! Please preview these points

2024-06-11 18:12 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/services/SendMoneyController.java
> +    public ResponseEntity<Transaction> sendMoney(@RequestBody Transaction request) {
You can skip using `ResponseEntity` and use directly `Transaction`.

2024-06-11 18:12 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/services/SendMoneyController.java
> +public class SendMoneyController {
You might move this class into a package `controller`.

2024-06-13 18:51 UTC, stephane-segning approved these changes

2024-06-14 08:48 UTC, sinke237 approved these changes

2024-06-14 09:00 UTC, NkwaTambe approved these changes

2024-06-14 09:01 UTC, AssahBismarkabah approved these changes

2024-06-14 09:03 UTC, AssahBismarkabah commented
hello @kouamschekina  the branch has conflicts with the base branch.

2024-06-14 09:38 UTC, merged