Linking pages of the front end
ADORSYS-GIS/e2e-banking-app pull request #143
Opened 2024-06-13 09:37 UTC by Motouom

@Arielpetit @Ngha-Boris @Koufan-De-King  please review this PR 

<img width="358" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/1e7224ea-a050-4fe5-879b-0632104ec936">

<img width="362" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/8666dbb7-058f-477c-9ad9-af2bd9b5dd10">

<img width="363" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/a09f1524-9ee5-440b-8053-6c55cfde49bb">

<img width="361" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/716b2a71-2f87-46d3-95cb-7823606fd7d0">

<img width="345" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/010b2051-d14d-4891-aaa7-96968a148f00">

<img width="347" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/661a61ed-79e7-4e72-8108-b03a45cb578a">

<img width="357" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/880740a0-9625-46db-abdd-a67db3309f22">

<img width="361" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/1f18cdb5-308b-483d-ac7d-9bc743e5856a">

<img width="343" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/7886dea6-b447-4933-916f-1071b3c2da03">

<img width="356" alt="image" src="https://github.com/ADORSYS-GIS/e2e-banking-app/assets/149515567/67e1da9c-06e6-429d-ab52-71170a239108">

2024-06-13 09:49 UTC, Koufan-De-King approved these changes
Great, @Motouom ! The routing configuration is well done. 
The alignment of the components such as the buttons and input fields should be worked on next.

2024-06-13 11:06 UTC, Motouom commented
> Great, @Motouom ! The routing configuration is well done. The alignment of the components such as the buttons and input fields should be worked on next.

Okay @Koufan-De-King

2024-06-13 11:08 UTC, Motouom commented
> > Great, @Motouom ! The routing configuration is well done. The alignment of the components such as the buttons and input fields should be worked on next.
> 
> Okay @Koufan-De-King

Done @Koufan-De-King  please can you review it again.

2024-06-13 11:40 UTC, Calebasah approved these changes
Well done!!, Mr @Motouom

2024-06-13 12:53 UTC, Koufan-De-King commented
> > > Great, @Motouom ! The routing configuration is well done. The alignment of the components such as the buttons and input fields should be worked on next.
> > 
> > 
> > Okay @Koufan-De-King
> 
> Done @Koufan-De-King please can you review it again.

Perfect @Motouom

2024-06-13 12:53 UTC, Koufan-De-King approved these changes

2024-06-13 12:59 UTC, Arielpetit requested changes
please @Motouom why is this file power-pay-frontend/src/components/scan_rq.tsx there? we used the useNavigate already and all the routs are in the App.tsx

2024-06-13 13:05 UTC, Arielpetit requested changes

2024-06-13 13:05 UTC, Arielpetit commented on power-pay-frontend/src/components/route.tsx
Mr @Motouom please what is the need of this file? since we used the useNavigate already and the routes are all in the App.tsx?

2024-06-13 13:05 UTC, Motouom commented
> please @Motouom why is this file power-pay-frontend/src/components/scan_rq.tsx there? we used the useNavigate already and all the routs are in the App.tsx

This file is the file for the scanner of the QR Code so it is essential. @Arielpetit

2024-06-13 13:17 UTC, Arielpetit approved these changes

2024-06-13 13:17 UTC, merged

2024-06-14 08:36 UTC, Ngha-Boris reviewed
Nice