Setup mapstruct into backend
ADORSYS-GIS/e2e-banking-app pull request #145
Opened 2024-06-14 14:06 UTC by kouamschekina

- Setup Mapstruct into Backend
- Implemented a test for the mapstruct

2024-06-15 08:36 UTC, Elwizzy12 approved these changes
great job!

2024-06-15 09:07 UTC, NkwaTambe approved these changes

2024-06-17 07:31 UTC, stephane-segning requested changes

2024-06-17 07:31 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/domain/model/Person.java
Do we need this in our business logic? If yes, what for?

2024-06-17 07:31 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/services/dto/PersonDto.java
Do we need this in our business logic? If yes, what for?

2024-06-17 07:31 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/utils/PersonMapper.java
Do we need this in our business logic? If yes, what for?

2024-06-17 08:48 UTC, Elwizzy12 commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/domain/model/Person.java
The Person class does not appear to be part of the core business logic. It is simply a sample implementation and may not be strictly required. The existing logic is functioning correctly with the current sample. So, depending on the specific requirements and design of this application, we can easily incorporate the Person class, data transfer object, and associated mappings by making the necessary modifications to fit the application's needs.

2024-06-19 07:25 UTC, stephane-segning requested changes
One last change:

2024-06-19 07:25 UTC, stephane-segning commented on power-pay-backend/src/test/java/com/adorsys/gis/powerpay/powerpaybackend/PersonMapper.java
> +@Mapper
Add the type component to this mapper, as we're working with Spring Boot.

https://www.baeldung.com/mapstruct#Injection

2024-06-19 10:45 UTC, stephane-segning approved these changes

2024-06-19 10:46 UTC, merged