Feature/translation service backend
ADORSYS-GIS/e2e-banking-app pull request #46
Opened 2024-03-03 12:39 UTC by AssahBismarkabah

added README file that describes the APIs for the Translation Service backend, including examples and diagrams. The section includes a description of the Twilio SMS Gateway API, the Translation Service API, and the PowerPay Service API, as well as a table summarizing the operations on the API endpoints.

2024-03-03 12:40 UTC, AssahBismarkabah commented
hello sir  @stephane-segning kindly review this PR

2024-03-03 14:09 UTC, stephane-segning requested changes
Good work overall @AssahBismarkabah! But you still need to refine some points. For starter, please remove all code blocks, as these might change. The architecture is good enough, so capitalize on that one.

2024-03-03 14:09 UTC, stephane-segning commented on power-pay-translator/README.md
> +# Architecture <a name="architecture"></a>
Also the Translation Service Backend:
- receive requests from the P.P.Service to send someone an SMS;
- this is the way we 
  - respond to user that send an SMS, or 
  - send someone OTP for login

2024-03-03 14:09 UTC, stephane-segning commented on power-pay-translator/README.md
> +# Technology
Even the logging tech for the rust app,...

2024-03-03 14:09 UTC, stephane-segning commented on power-pay-translator/README.md
> +![alt text](image.png)
Please do your graphs and illustrations using [mermaid flowchart](https://mermaid.js.org/syntax/flowchart.html)

2024-03-03 14:09 UTC, stephane-segning commented on power-pay-translator/README.md
> +````js
This code is using https://crates.io/crates/twilio. Did you check it is correct?

2024-03-03 14:09 UTC, stephane-segning commented on power-pay-translator/README.md
> +````js
If yes, nice. But remove it anyway. Just put the name of the lib used

2024-03-03 14:10 UTC, stephane-segning commented
@AssahBismarkabah you think it'll be better to have two entry point Endpoints on the translation service, named `/messages` and `/transfers`? Remember that twilio is calling your app only on one place.

2024-03-03 14:13 UTC, stephane-segning commented
Wouldn't it be better to have one, which will then translate into the multitude for calling the P.P.Service? That way another endpoint could just be the `/health`, for checking on the server

2024-03-03 14:26 UTC, AssahBismarkabah commented
ok sir @stephane-segning   i will do the changes now

2024-03-03 19:55 UTC, AssahBismarkabah commented on power-pay-translator/README.md
> +### Database:
ok sir @stephane-segning  i get the reason now

2024-03-03 20:57 UTC, AssahBismarkabah commented
hello sir @stephane-segning  for the  entry point Endpoints on the translation service i named it  /messages  the other endpoints are the proposed endpoint for the power powerpay service

2024-03-04 20:04 UTC, AssahBismarkabah commented
hello sir @stephane-segning did the recommended modifications and added the sequence diagram involving the end poits

2024-03-05 08:35 UTC, stephane-segning commented
@AssahBismarkabah good work. Please put your changes in a `.md` file under the doc folder

2024-03-05 08:38 UTC, stephane-segning requested changes
Good work. Please proceed to the changes

2024-03-05 08:38 UTC, stephane-segning commented on power-pay-translator/README.md
> +| Endpoint | Method |Description |
You're making a confusion here. `/handle_messages` and `/send_sms` are present on the Translator service (TS). The two others are on the PPService and the TS is calling that

2024-03-05 11:31 UTC, stephane-segning commented
You're making a confusion here. /handle_messages and /send_sms are present on the Translator service (TS). The two others are on the PPService and the TS is calling that

2024-03-05 13:03 UTC, AssahBismarkabah commented
hello sir @stephane-segning did the necessary modifications sir.

2024-03-05 19:52 UTC, merged

2024-03-05 19:52 UTC, stephane-segning commented
Awesome work!