Add a (css-tailwind.md)file in the docs/
ADORSYS-GIS/e2e-banking-app pull request #69
Opened 2024-03-06 13:46 UTC by Ogenbertrand

I created a md file for the tailwind css system design

2024-03-06 13:50 UTC, Ogenbertrand commented
@stephane-segning pr for ticket [Setup css design system](https://github.com/ADORSYS-GIS/e2e-banking-app/issues/49)

2024-03-06 17:32 UTC, stephane-segning approved these changes
Good work!

2024-03-07 10:57 UTC, Ogenbertrand commented
@Ogenbertrand
[generate a tailwind.config.js file in the power-pay-frontend/](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/151c470966cf3cedad68e6dea25b475a2312091e)

2024-03-07 11:12 UTC, stephane-segning requested changes
Good work overall @Ogenbertrand! Please address these points so that we can go forward

2024-03-07 11:12 UTC, stephane-segning commented on power-pay-frontend/src/App.css
I don't think we need this

2024-03-07 11:12 UTC, stephane-segning commented on power-pay-frontend/tailwind.config.js
This is not wrong, but not adapted to our project. Watch these guidelines https://tailwindcss.com/docs/guides/vite

2024-03-07 12:02 UTC, Ogenbertrand commented on power-pay-frontend/tailwind.config.js
Ok @stephane-segning  i'll work on that just now .

2024-03-08 07:45 UTC, Ogenbertrand commented
@stephane-segning 
[create a new config file (/power-pay-frontend/tailwind.config.ts)](https://github.com/ADORSYS-GIS/e2e-banking-app/commit/6971300d7b0fc6459a29ee7196dd136abf4636d1)

2024-03-08 08:18 UTC, stephane-segning requested changes
You created a new frontend project `e2e-banking-app-tailwind`, while the question was for you to add `tailwindcss` to the already existing project. Remove the e2e-banking-app-tailwind folder first. Then proceed on the ticket.

2024-03-08 08:46 UTC, Ogenbertrand commented
@stephane-segning 
@Ogenbertrand
[dicard the (e2e-banking-app-tailwind/) from the project working dir](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/14cb7ffa5dee10a8cbeac792277ba0afd1d9c57d)

2024-03-08 12:41 UTC, stephane-segning requested changes

2024-03-08 12:41 UTC, stephane-segning commented on power-pay-frontend/src/App.css
Cancel these changes

2024-03-08 12:41 UTC, stephane-segning commented on power-pay-frontend/package.json
Why removing `sass` and not adding `tailwindcss`?

2024-03-08 13:24 UTC, Ogenbertrand commented on power-pay-frontend/package.json
I removed sass because i had some conflicts in the package.json file, i just i identified my error,
creating the package.json file i didn't install the dependencies which i just did now.

2024-03-11 12:34 UTC, Ogenbertrand commented
@stephane-segning i added a postcss config file in the powerpay directory.
[Add a config file for postcss in power-pay-frontend/](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/0ecfdf04cca0a6ffcdd157e52950c3e556296046)

2024-03-11 13:12 UTC, Ogenbertrand commented
@stephane-segning  i added a config file for postcss 
[Add a config file for potscss in power-pay-frontend/](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/43d305518c6df5c73cf2c59a8cde4a93732ce707)

2024-03-11 13:17 UTC, Ogenbertrand commented
@stephane-segning i just added a config file for postcss 
[Add a config file for potscss in power-pay-frontend/](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/43d305518c6df5c73cf2c59a8cde4a93732ce707)

2024-03-12 07:31 UTC, Ogenbertrand commented
@stephane-segning 
[creat a new package.lock.json file in the power-pay-frontend/](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/419441c36d0eec42871ecd732f3831ff98f769f7)

2024-03-12 07:55 UTC, Ogenbertrand commented
@stephane-segning 
[define a build script in the script section of the power-pay-frontend…](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/2d423aaf10d8757eab22a5e4aaa8f334a395f1e6)

2024-03-12 10:38 UTC, Ogenbertrand commented
@stephane-segning 
[edit the postcss.config.js to postcss.config.cjs file](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/0c7d0eceeee45459bd569f3f798c863a824c1fad)

2024-03-12 10:43 UTC, stephane-segning requested changes

2024-03-12 10:43 UTC, stephane-segning commented on power-pay-frontend/package.json
> +    "vite": "^5.0.4",
Why downgrade the vite version?

2024-03-12 10:43 UTC, stephane-segning commented on power-pay-frontend/package.json
> +
Why the empty space here?

2024-03-12 10:53 UTC, Ogenbertrand commented
@stephane-segning 
[add a new version of vite in package.json file](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/647de37fa1cfd079b6a5260414455365c720cf5d)

2024-03-12 11:13 UTC, stephane-segning requested changes

2024-03-12 11:13 UTC, stephane-segning commented on power-pay-frontend/package.json
> +    "start": "react-scripts start",
Why react-scripts, while we're using `vite` ? Read again about react with vite [here](https://vitejs.dev/guide/).

2024-03-12 11:13 UTC, stephane-segning commented on power-pay-frontend/package.json
> +  "homepage": "https://adorsys-gis.github.io/e2e-banking-app",
Why changing this?

2024-03-12 12:34 UTC, Ogenbertrand commented
@stephane-segning 
[the start script is set vite in package.json file](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/6c0e8a226a60530f25d9bcc6fbb25f3209fa4eef)

2024-03-14 15:01 UTC, Ogenbertrand commented
@stephane-segning 
I just applied the changes in the package.json file
[Add a sass package in the package.json file.](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/8340b7ae8ae5399ad2ff775c356d874f6bc5ac04)

2024-03-15 03:24 UTC, Ogenbertrand commented
@stephane-segning 
@Ogenbertrand
[Update script: Remove placeholder 'test' command](https://github.com/ADORSYS-GIS/e2e-banking-app/pull/69/commits/fc1784b6ad15fb294f8e18077086313feb19fd8c)

2024-03-19 10:10 UTC, stephane-segning approved these changes
Good work @Ogenbertrand !

2024-03-19 10:10 UTC, merged