Setup  sass-based css design system #49
ADORSYS-GIS/e2e-banking-app pull request #72
Opened 2024-03-06 22:42 UTC by nancymuyeh

@stephane-segning , PR for the implementation of sass-based css design system.

2024-03-07 07:02 UTC, stephane-segning requested changes
Please remove everything about gulp, as react vite already supports sass

2024-03-07 11:17 UTC, stephane-segning requested changes

2024-03-07 11:17 UTC, stephane-segning commented on docs/sass_usage.md
> +# installation
You should probably also update your doc, because this is very general. In our case, we're using `vite` & `react`

2024-03-07 12:55 UTC, nancymuyeh commented on power-pay-frontend/sass/index.scss
Should I remove the index.scss file as well?

2024-03-07 21:16 UTC, stephane-segning requested changes
Good work overall. Better doc too!

2024-03-08 01:51 UTC, nancymuyeh commented on power-pay-frontend/src/index.scss
Done

2024-03-08 03:01 UTC, stephane-segning approved these changes
Awesome! Thank you @nancymuyeh!

2024-03-08 03:02 UTC, merged