Feat/63 implement health endpoint
ADORSYS-GIS/e2e-banking-app pull request #79
Opened 2024-03-07 16:51 UTC by Awambeng

added the unit test for the health endpoint

2024-03-07 16:53 UTC, Awambeng commented
@stephane-segning please review the last point under ticket [Implement health Endpoint for Health Check in PowerPay Server #63](https://github.com/ADORSYS-GIS/e2e-banking-app/issues/63)

2024-03-07 21:53 UTC, stephane-segning requested changes
Good work @chendiblessing!

2024-03-07 21:53 UTC, stephane-segning commented on power-pay-backend/pom.xml
> -            <scope>test</scope>
Why are you removing this scope `test`?

2024-03-07 21:53 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/controller/HealthController.java
This is already provided by actuator. No need to implement it yourself. But good attempt!

2024-03-08 07:47 UTC, chendiblessing commented
@stephane-segning i have made the changes you requested

2024-03-09 18:35 UTC, stephane-segning requested changes

2024-03-09 18:35 UTC, stephane-segning commented on power-pay-backend/src/main/java/com/adorsys/gis/powerpay/powerpaybackend/controller/HealthController.java
Remove this. Actuator already provides this for you.

2024-03-09 18:59 UTC, Awambeng commented
Prof @stephane-segning changes done

2024-03-09 22:38 UTC, stephane-segning requested changes

2024-03-09 22:38 UTC, stephane-segning commented on power-pay-backend/pom.xml
> +<!--         <dependency>
What is this change?

2024-03-09 22:38 UTC, stephane-segning commented on power-pay-backend/src/test/java/com/adorsys/gis/powerpay/powerpaybackend/PowerPayBackendHealthTest.java
> +public class PowerPayBackendHealthTest {
This is testing the best case. You should also test the case the server is not sending 200 ok

2024-03-11 11:29 UTC, Awambeng commented
hello prof @stephane-segning i did the last changes you demanded please you can now review

2024-03-11 19:35 UTC, Awambeng commented
@stephane-segning everything well done

2024-03-19 10:14 UTC, stephane-segning approved these changes
Good work Dr @Awambeng !

2024-03-19 10:15 UTC, merged