Setup mapstruct into backend
ADORSYS-GIS/e2e-banking-app pull request #95
Opened 2024-03-11 10:11 UTC by Elwizzy12

@stephane-segning Was tasked to implement mapstruct into the backend and write a test file to ensure everything works.
Please review!!!

2024-03-11 18:12 UTC, stephane-segning requested changes
Good work @Elwizzy12. Please watch this

2024-03-11 18:12 UTC, stephane-segning commented on power-pay-backend/src/test/java/com/adorsys/gis/powerpay/powerpaybackend/Person.java
Put this class inside an inner class inside of the `MapstructTest`.

2024-03-11 18:12 UTC, stephane-segning commented on power-pay-backend/src/test/java/com/adorsys/gis/powerpay/powerpaybackend/PersonDto.java
Put this class inside an inner class inside of the `MapstructTest`.

2024-03-11 18:12 UTC, stephane-segning commented on power-pay-backend/src/test/java/com/adorsys/gis/powerpay/powerpaybackend/PersonMapper.java
Put this class inside an inner class inside of the `MapstructTest`.

2024-06-14 08:38 UTC, stephane-segning approved these changes

2024-06-14 10:37 UTC, NkwaTambe approved these changes

2024-06-14 10:52 UTC, Arielpetit approved these changes

2024-06-14 10:54 UTC, ArmandMeppa approved these changes

2024-06-18 13:48 UTC, Motouom commented
@Elwizzy12  please look for why your ticket can't be merged and fix it

2024-06-20 13:00 UTC, closed without merging