Add documentation on Lombok usage in Spring Boot projects
ADORSYS-GIS/e2e-banking-app pull request #96
Opened 2024-03-11 18:50 UTC by Awambeng

2024-03-11 18:51 UTC, Awambeng commented
@stephane-segning pr for [Research and explain Lombok #84](https://github.com/ADORSYS-GIS/e2e-banking-app/issues/84)

2024-03-11 21:45 UTC, Awambeng commented
@stephane-segning work done

2024-03-12 06:41 UTC, stephane-segning requested changes

2024-03-12 06:41 UTC, stephane-segning commented on docs/lombok_guide.md
> +public class User {
Take an example with contextual values (User vs Author)

2024-03-13 05:20 UTC, stephane-segning approved these changes
Good work

2024-03-13 05:21 UTC, merged

2024-03-13 06:32 UTC, Awambeng commented
Thanks prof @stephane-segning